include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false

    # without more complex parsing/generation logic enums must allow lowercase
    constant_identifier_names: false
